#!/bin/bash
#
# update the repository
#

cd "`dirname \"$0\"`"

(
  date
  hash_old="`git log -n 1 --pretty=format:'%H'`"
  git pull
  hash_new="`git log -n 1 --pretty=format:'%H'`"
  if [ "$hash_old" != "$hash_new" ]; then
    echo "Updated. Restarting!"
    echo sudo reboot
  fi
) | tee -a update.log
